export const adminCourses = [
  {
    id: '1',
    title: 'React Masterclass',
    instructor: 'Jane Smith',
    mod: 'Alice Johnson',
    status: 'Published',
    price: 99.99,
    students: 1250,
    rating: 4.8,
    reviews: 89,
    createdDate: '2024-01-15',
    lastUpdated: '2024-11-15',
    category: 'Programming',
  },
  {
    id: '2',
    title: 'Advanced JavaScript',
    instructor: 'Bob Wilson',
    mod: 'Alice Johnson',
    status: 'Under Review',
    price: 149.99,
    students: 0,
    rating: 0,
    reviews: 0,
    createdDate: '2024-11-10',
    lastUpdated: '2024-11-10',
    category: 'Programming',
  },
  {
    id: '3',
    title: 'Python for Data Science',
    instructor: 'Charlie Brown',
    mod: 'David Lee',
    status: 'Published',
    price: 199.99,
    students: 890,
    rating: 4.6,
    reviews: 67,
    createdDate: '2024-03-22',
    lastUpdated: '2024-10-05',
    category: 'Data Science',
  },
  {
    id: '4',
    title: 'UI/UX Design Fundamentals',
    instructor: 'Diana Prince',
    mod: 'Alice Johnson',
    status: 'Under Review',
    price: 79.99,
    students: 0,
    rating: 0,
    reviews: 0,
    createdDate: '2024-10-01',
    lastUpdated: '2024-10-15',
    category: 'Design',
  },
  {
    id: '5',
    title: 'Machine Learning Basics',
    instructor: 'Eve Garcia',
    mod: 'David Lee',
    status: 'Rejected',
    price: 249.99,
    students: 0,
    rating: 0,
    reviews: 0,
    createdDate: '2024-09-15',
    lastUpdated: '2024-09-20',
    category: 'AI/ML',
  },
]
