// Mock data for mod reports management
export const reports = [
  {
    id: '1',
    studentName: 'John Doe',
    studentEmail: 'john.doe@example.com',
    courseTitle: 'React Masterclass',
    courseId: 'C001',
    reportType: 'Inappropriate Content',
    description: 'Course contains offensive language and inappropriate examples',
    submittedDate: '2024-11-20 14:30',
    status: 'Pending',
    evidence: ['screenshot1.jpg', 'screenshot2.jpg'],
    category: 'content'
  },
  {
    id: '2',
    studentName: 'Alice Brown',
    studentEmail: 'alice.brown@example.com',
    courseTitle: 'Python for Data Science',
    courseId: 'C004',
    reportType: 'Copyright Infringement',
    description: 'Course content appears to be copied from another platform',
    submittedDate: '2024-11-19 10:15',
    status: 'Pending',
    evidence: ['comparison.pdf'],
    category: 'copyright'
  },
  {
    id: '3',
    studentName: 'Charlie Wilson',
    studentEmail: 'charlie.wilson@example.com',
    courseTitle: 'Web Development Bootcamp',
    courseId: 'C003',
    reportType: 'Technical Issues',
    description: 'Course videos are not loading properly, poor audio quality',
    submittedDate: '2024-11-18 16:45',
    status: 'Resolved',
    evidence: ['video_error.mp4'],
    category: 'technical',
    resolution: 'Fixed video streaming issues, improved audio quality',
    resolvedDate: '2024-11-19'
  },
  {
    id: '4',
    studentName: 'Diana Prince',
    studentEmail: 'diana.prince@example.com',
    courseTitle: 'Advanced JavaScript',
    courseId: 'C002',
    reportType: 'Instructor Behavior',
    description: 'Instructor is unresponsive to student questions in discussion forum',
    submittedDate: '2024-11-17 09:20',
    status: 'Resolved',
    evidence: ['forum_screenshot.png'],
    category: 'behavior',
    resolution: 'Contacted instructor, reminded of response time requirements',
    resolvedDate: '2024-11-18'
  },
  {
    id: '5',
    studentName: 'Mike Johnson',
    studentEmail: 'mike.johnson@example.com',
    courseTitle: 'Machine Learning Basics',
    courseId: 'C005',
    reportType: 'Spam Content',
    description: 'Course contains promotional links and spam content',
    submittedDate: '2024-11-16 11:30',
    status: 'Resolved',
    evidence: ['spam_content.pdf'],
    category: 'spam',
    resolution: 'Report found to be unsubstantiated, course content verified as legitimate',
    resolvedDate: '2024-11-17'
  },
]
