// Mock data for development when backend is not available

export const mockCategories = [
  {
    id: "cat-1",
    name: "Web Development",
    description: "Learn to build websites and web applications",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "cat-2",
    name: "Mobile Development",
    description: "Create mobile apps for iOS and Android",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "cat-3",
    name: "Data Science",
    description: "Master data analysis and machine learning",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "cat-4",
    name: "Design",
    description: "UI/UX design and graphic design skills",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "cat-5",
    name: "Business",
    description: "Business strategy and entrepreneurship",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
];

export const mockCourses = [
  {
    id: "course-1",
    instructorId: "inst-1",
    title: "Complete React Developer Bootcamp",
    subtitle: "From Zero to Hero: Master Modern React Development",
    description: "Master React from basics to advanced concepts. Build real-world applications with modern React patterns and best practices. This comprehensive course covers everything you need to become a professional React developer.",
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=225&fit=crop",
    trailerVideo: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    status: "Published",
    duration: 2400, // 40 hours in minutes
    price: 89.99,
    level: "Intermediate",
    categoryId: "cat-1",
    language: "English",
    numberOfReviews: 1250,
    averageRating: 4.7,
    totalStudents: 15420,
    lastUpdated: "2024-10-15",
    certificate: true,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[0],
    instructor: {
      id: "inst-1",
      name: "John Smith",
      profilePicture: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=64&h=64&fit=crop&crop=face",
      bio: "Senior Software Engineer with 8+ years of experience in React and modern web technologies. Former Google engineer and startup founder.",
      rating: 4.9,
      studentsCount: 45000,
      coursesCount: 12,
    },
    whatYouWillLearn: [
      "Build complete React applications from scratch",
      "Master React Hooks, Context API, and Redux",
      "Learn modern React patterns and best practices",
      "Create responsive, mobile-first applications",
      "Implement authentication and authorization",
      "Deploy applications to production environments",
      "Write clean, maintainable, and scalable code"
    ],
    requirements: [
      "Basic knowledge of HTML, CSS, and JavaScript",
      "Understanding of ES6+ features",
      "Familiarity with npm and package management"
    ],
    targetAudience: [
      "Beginner to intermediate developers wanting to learn React",
      "Developers looking to upgrade their React skills",
      "Anyone interested in modern web development",
      "Students preparing for React developer positions"
    ],
    curriculum: [
      {
        id: "section-1",
        title: "Getting Started with React",
        duration: 180,
        lectures: [
          { id: "lec-1", title: "Course Introduction", duration: 15, type: "video", preview: true },
          { id: "lec-2", title: "Setting up Development Environment", duration: 25, type: "video", preview: true },
          { id: "lec-3", title: "Understanding React Components", duration: 30, type: "video" },
          { id: "lec-4", title: "JSX and Virtual DOM", duration: 35, type: "video" },
          { id: "lec-5", title: "First React Application", duration: 45, type: "video" },
          { id: "lec-6", title: "React Fundamentals Quiz", duration: 30, type: "quiz" }
        ]
      },
      {
        id: "section-2",
        title: "React Hooks and State Management",
        duration: 240,
        lectures: [
          { id: "lec-7", title: "Introduction to Hooks", duration: 20, type: "video" },
          { id: "lec-8", title: "useState Hook Deep Dive", duration: 35, type: "video" },
          { id: "lec-9", title: "useEffect Hook", duration: 40, type: "video" },
          { id: "lec-10", title: "Custom Hooks", duration: 30, type: "video" },
          { id: "lec-11", title: "Context API", duration: 45, type: "video" },
          { id: "lec-12", title: "State Management Patterns", duration: 50, type: "video" },
          { id: "lec-13", title: "Hooks Quiz", duration: 20, type: "quiz" }
        ]
      },
      {
        id: "section-3",
        title: "Advanced React Concepts",
        duration: 300,
        lectures: [
          { id: "lec-14", title: "Higher-Order Components", duration: 35, type: "video" },
          { id: "lec-15", title: "Render Props Pattern", duration: 40, type: "video" },
          { id: "lec-16", title: "React Performance Optimization", duration: 55, type: "video" },
          { id: "lec-17", title: "Error Boundaries", duration: 25, type: "video" },
          { id: "lec-18", title: "React Testing", duration: 60, type: "video" },
          { id: "lec-19", title: "Advanced Patterns Quiz", duration: 25, type: "quiz" },
          { id: "lec-20", title: "Final Project", duration: 60, type: "assignment" }
        ]
      }
    ],
    reviews: [
      {
        id: "review-1",
        userId: "user-1",
        rating: 5,
        comment: "Excellent course! John explains everything clearly and the projects are very practical. Highly recommended!",
        createdBy: "user-1",
        user: {
          id: "user-1",
          name: "Sarah Johnson",
          avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=40&h=40&fit=crop&crop=face"
        }
      },
      {
        id: "review-2",
        userId: "user-2",
        rating: 5,
        comment: "This course transformed my career. The content is up-to-date and the teaching method is outstanding.",
        createdBy: "user-2",
        user: {
          id: "user-2",
          name: "Mike Chen",
          avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face"
        }
      }
    ]
  },
  {
    id: "course-2",
    instructorId: "inst-2",
    title: "Python for Data Science & Machine Learning",
    subtitle: "Master Data Analysis, Visualization & Machine Learning with Python",
    description: "Complete Python course for data science and machine learning. Learn pandas, numpy, matplotlib, scikit-learn, and more. Build real-world data science projects from scratch.",
    thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=225&fit=crop",
    trailerVideo: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    status: "Published",
    duration: 3600, // 60 hours
    price: 0, // Free
    level: "Beginner",
    categoryId: "cat-3",
    language: "English",
    numberOfReviews: 2100,
    averageRating: 4.8,
    totalStudents: 89450,
    lastUpdated: "2024-09-20",
    certificate: true,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[2],
    instructor: {
      id: "inst-2",
      name: "Sarah Johnson",
      profilePicture: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=64&h=64&fit=crop&crop=face",
      bio: "Data Scientist and Machine Learning Engineer at Google. PhD in Computer Science with 10+ years of experience in AI and data science.",
      rating: 4.9,
      studentsCount: 125000,
      coursesCount: 8,
    },
    whatYouWillLearn: [
      "Master Python programming fundamentals",
      "Data manipulation with pandas and numpy",
      "Data visualization with matplotlib and seaborn",
      "Machine learning with scikit-learn",
      "Statistical analysis and hypothesis testing",
      "Build predictive models and algorithms",
      "Work with real datasets and case studies"
    ],
    requirements: [
      "Basic computer skills",
      "No prior programming experience required",
      "Access to a computer with internet connection"
    ],
    targetAudience: [
      "Complete beginners interested in data science",
      "Programmers wanting to learn Python",
      "Students pursuing data science careers",
      "Professionals looking to upskill in ML",
      "Anyone interested in data analysis"
    ],
    curriculum: [
      {
        id: "section-1",
        title: "Python Fundamentals",
        duration: 240,
        lectures: [
          { id: "lec-1", title: "Introduction to Python", duration: 20, type: "video", preview: true },
          { id: "lec-2", title: "Installing Python and Setup", duration: 15, type: "video", preview: true },
          { id: "lec-3", title: "Variables and Data Types", duration: 25, type: "video" },
          { id: "lec-4", title: "Control Structures", duration: 35, type: "video" },
          { id: "lec-5", title: "Functions and Modules", duration: 40, type: "video" },
          { id: "lec-6", title: "Python Fundamentals Quiz", duration: 25, type: "quiz" }
        ]
      },
      {
        id: "section-2",
        title: "Data Analysis with Pandas",
        duration: 300,
        lectures: [
          { id: "lec-7", title: "Introduction to Pandas", duration: 30, type: "video" },
          { id: "lec-8", title: "DataFrames and Series", duration: 45, type: "video" },
          { id: "lec-9", title: "Data Cleaning and Preprocessing", duration: 50, type: "video" },
          { id: "lec-10", title: "Data Aggregation and Grouping", duration: 40, type: "video" },
          { id: "lec-11", title: "Merging and Joining Data", duration: 35, type: "video" },
          { id: "lec-12", title: "Data Analysis Project", duration: 60, type: "assignment" },
          { id: "lec-13", title: "Pandas Quiz", duration: 20, type: "quiz" }
        ]
      },
      {
        id: "section-3",
        title: "Data Visualization",
        duration: 180,
        lectures: [
          { id: "lec-14", title: "Introduction to Matplotlib", duration: 30, type: "video" },
          { id: "lec-15", title: "Advanced Plotting with Seaborn", duration: 40, type: "video" },
          { id: "lec-16", title: "Interactive Visualizations", duration: 35, type: "video" },
          { id: "lec-17", title: "Visualization Project", duration: 55, type: "assignment" },
          { id: "lec-18", title: "Visualization Quiz", duration: 20, type: "quiz" }
        ]
      },
      {
        id: "section-4",
        title: "Machine Learning with Scikit-learn",
        duration: 360,
        lectures: [
          { id: "lec-19", title: "Introduction to Machine Learning", duration: 40, type: "video" },
          { id: "lec-20", title: "Supervised Learning Algorithms", duration: 60, type: "video" },
          { id: "lec-21", title: "Unsupervised Learning", duration: 50, type: "video" },
          { id: "lec-22", title: "Model Evaluation and Validation", duration: 45, type: "video" },
          { id: "lec-23", title: "Feature Engineering", duration: 35, type: "video" },
          { id: "lec-24", title: "ML Project: Predictive Modeling", duration: 70, type: "assignment" },
          { id: "lec-25", title: "Machine Learning Quiz", duration: 30, type: "quiz" }
        ]
      }
    ],
    reviews: [
      {
        id: "review-3",
        userId: "user-3",
        rating: 5,
        comment: "Perfect course for beginners! Sarah explains everything so clearly. I went from knowing nothing about Python to building ML models.",
        createdBy: "user-3",
        user: {
          id: "user-3",
          name: "Alex Chen",
          avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=40&h=40&fit=crop&crop=face"
        }
      },
      {
        id: "review-4",
        userId: "user-4",
        rating: 5,
        comment: "Free course with incredible quality! The projects are very practical and the instructor is amazing. Highly recommended!",
        createdBy: "user-4",
        user: {
          id: "user-4",
          name: "Maria Garcia",
          avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=40&h=40&fit=crop&crop=face"
        }
      }
    ]
  },
  {
    id: "course-3",
    instructorId: "inst-3",
    title: "iOS Development with SwiftUI",
    description: "Build beautiful iOS apps using SwiftUI framework. Learn declarative UI development and modern iOS patterns.",
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=225&fit=crop",
    status: "Published",
    duration: 3000, // 50 hours
    price: 119.99,
    level: "Intermediate",
    categoryId: "cat-2",
    language: "English",
    numberOfReviews: 890,
    averageRating: 4.6,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[1],
    instructor: {
      id: "inst-3",
      name: "Mike Chen",
      profilePicture: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-4",
    instructorId: "inst-4",
    title: "UI/UX Design Masterclass",
    description: "Complete guide to user interface and user experience design. From wireframes to prototypes using Figma.",
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=225&fit=crop",
    status: "Published",
    duration: 1800, // 30 hours
    price: 79.99,
    level: "Beginner",
    categoryId: "cat-4",
    language: "English",
    numberOfReviews: 650,
    averageRating: 4.5,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[3],
    instructor: {
      id: "inst-4",
      name: "Emily Davis",
      profilePicture: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-5",
    instructorId: "inst-5",
    title: "Node.js Backend Development",
    description: "Build scalable backend applications with Node.js, Express, and MongoDB. REST APIs and GraphQL.",
    thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=225&fit=crop",
    status: "Published",
    duration: 2700, // 45 hours
    price: 94.99,
    level: "Intermediate",
    categoryId: "cat-1",
    language: "English",
    numberOfReviews: 980,
    averageRating: 4.4,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[0],
    instructor: {
      id: "inst-5",
      name: "David Wilson",
      profilePicture: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-6",
    instructorId: "inst-6",
    title: "Digital Marketing Strategy",
    description: "Master digital marketing from SEO to social media. Build comprehensive marketing strategies for businesses.",
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=225&fit=crop",
    status: "Published",
    duration: 2100, // 35 hours
    price: 69.99,
    level: "Beginner",
    categoryId: "cat-5",
    language: "English",
    numberOfReviews: 720,
    averageRating: 4.3,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[4],
    instructor: {
      id: "inst-6",
      name: "Lisa Anderson",
      profilePicture: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-7",
    instructorId: "inst-7",
    title: "Advanced JavaScript Concepts",
    description: "Deep dive into advanced JavaScript topics: closures, prototypes, async programming, and modern ES6+ features.",
    thumbnail: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=400&h=225&fit=crop",
    status: "Published",
    duration: 3300, // 55 hours
    price: 129.99,
    level: "Advanced",
    categoryId: "cat-1",
    language: "English",
    numberOfReviews: 560,
    averageRating: 4.6,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[0],
    instructor: {
      id: "inst-7",
      name: "Alex Rodriguez",
      profilePicture: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-8",
    instructorId: "inst-8",
    title: "Flutter Mobile App Development",
    description: "Create cross-platform mobile apps with Flutter and Dart. From basics to advanced state management.",
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=225&fit=crop",
    status: "Published",
    duration: 3900, // 65 hours
    price: 109.99,
    level: "Intermediate",
    categoryId: "cat-2",
    language: "English",
    numberOfReviews: 430,
    averageRating: 4.7,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[1],
    instructor: {
      id: "inst-8",
      name: "Rachel Kim",
      profilePicture: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-9",
    instructorId: "inst-9",
    title: "Machine Learning with TensorFlow",
    description: "Learn machine learning and deep learning with TensorFlow. Build and deploy ML models from scratch.",
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=225&fit=crop",
    status: "Published",
    duration: 4200, // 70 hours
    price: 149.99,
    level: "Advanced",
    categoryId: "cat-3",
    language: "English",
    numberOfReviews: 340,
    averageRating: 4.8,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[2],
    instructor: {
      id: "inst-9",
      name: "Dr. Michael Lee",
      profilePicture: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-10",
    instructorId: "inst-10",
    title: "Graphic Design Fundamentals",
    description: "Master the fundamentals of graphic design. Learn Adobe Creative Suite and design principles.",
    thumbnail: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400&h=225&fit=crop",
    status: "Published",
    duration: 2400, // 40 hours
    price: 84.99,
    level: "Beginner",
    categoryId: "cat-4",
    language: "English",
    numberOfReviews: 780,
    averageRating: 4.4,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[3],
    instructor: {
      id: "inst-10",
      name: "Tom Garcia",
      profilePicture: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-11",
    instructorId: "inst-11",
    title: "Startup Business Planning",
    description: "Learn how to create a winning business plan for your startup. From idea validation to funding strategies.",
    thumbnail: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=225&fit=crop",
    status: "Published",
    duration: 1800, // 30 hours
    price: 59.99,
    level: "Beginner",
    categoryId: "cat-5",
    language: "English",
    numberOfReviews: 290,
    averageRating: 4.2,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[4],
    instructor: {
      id: "inst-11",
      name: "Jennifer White",
      profilePicture: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-12",
    instructorId: "inst-12",
    title: "Vue.js 3 Complete Guide",
    description: "Master Vue.js 3 with Composition API, Pinia state management, and modern frontend development practices.",
    thumbnail: "https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=400&h=225&fit=crop",
    status: "Published",
    duration: 2700, // 45 hours
    price: 99.99,
    level: "Intermediate",
    categoryId: "cat-1",
    language: "English",
    numberOfReviews: 420,
    averageRating: 4.5,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[0],
    instructor: {
      id: "inst-12",
      name: "Kevin Brown",
      profilePicture: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=64&h=64&fit=crop&crop=face",
    },
  },
];
