// Mock data for development when backend is not available

import type { Course } from "@/types/db/course";

export const mockCategories = [
  {
    id: "cat-1",
    name: "Web Development",
    description: "Learn to build websites and web applications",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "cat-2",
    name: "Mobile Development",
    description: "Create mobile apps for iOS and Android",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "cat-3",
    name: "Data Science",
    description: "Master data analysis and machine learning",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "cat-4",
    name: "Design",
    description: "UI/UX design and graphic design skills",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
  {
    id: "cat-5",
    name: "Business",
    description: "Business strategy and entrepreneurship",
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
  },
];

export const mockCourses = [
  {
    id: "course-1",
    instructorId: "inst-1",
    title: "Complete React Developer Bootcamp",
    subtitle: "From Zero to Hero: Master Modern React Development",
    description:
      "Master React from basics to advanced concepts. Build real-world applications with modern React patterns and best practices. This comprehensive course covers everything you need to become a professional React developer.",
    thumbnail:
      "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=225&fit=crop",
    trailerVideo:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    status: "Published",
    duration: 2400, // 40 hours in minutes
    price: 89.99,
    level: "Intermediate",
    categoryId: "cat-1",
    language: "English",
    numberOfReviews: 1250,
    averageRating: 4.7,
    totalStudents: 15420,
    lastUpdated: "2024-10-15",
    certificate: true,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[0],
    instructor: {
      id: "inst-1",
      name: "John Smith",
      profilePicture:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=64&h=64&fit=crop&crop=face",
      bio: "Senior Software Engineer with 8+ years of experience in React and modern web technologies. Former Google engineer and startup founder.",
      rating: 4.9,
      studentsCount: 45000,
      coursesCount: 12,
    },
    whatYouWillLearn: [
      "Build complete React applications from scratch",
      "Master React Hooks, Context API, and Redux",
      "Learn modern React patterns and best practices",
      "Create responsive, mobile-first applications",
      "Implement authentication and authorization",
      "Deploy applications to production environments",
      "Write clean, maintainable, and scalable code",
    ],
    requirements: [
      "Basic knowledge of HTML, CSS, and JavaScript",
      "Understanding of ES6+ features",
      "Familiarity with npm and package management",
    ],
    targetAudience: [
      "Beginner to intermediate developers wanting to learn React",
      "Developers looking to upgrade their React skills",
      "Anyone interested in modern web development",
      "Students preparing for React developer positions",
    ],
    curriculum: [
      {
        id: "section-1",
        title: "Getting Started with React",
        duration: 180,
        lectures: [
          {
            id: "lec-1",
            title: "Course Introduction",
            duration: 15,
            type: "video",
            preview: true,
          },
          {
            id: "lec-2",
            title: "Setting up Development Environment",
            duration: 25,
            type: "video",
            preview: true,
          },
          {
            id: "lec-3",
            title: "Understanding React Components",
            duration: 30,
            type: "video",
          },
          {
            id: "lec-4",
            title: "JSX and Virtual DOM",
            duration: 35,
            type: "video",
          },
          {
            id: "lec-5",
            title: "First React Application",
            duration: 45,
            type: "video",
          },
          {
            id: "lec-6",
            title: "React Fundamentals Quiz",
            duration: 30,
            type: "quiz",
          },
        ],
      },
      {
        id: "section-2",
        title: "React Hooks and State Management",
        duration: 240,
        lectures: [
          {
            id: "lec-7",
            title: "Introduction to Hooks",
            duration: 20,
            type: "video",
          },
          {
            id: "lec-8",
            title: "useState Hook Deep Dive",
            duration: 35,
            type: "video",
          },
          { id: "lec-9", title: "useEffect Hook", duration: 40, type: "video" },
          { id: "lec-10", title: "Custom Hooks", duration: 30, type: "video" },
          { id: "lec-11", title: "Context API", duration: 45, type: "video" },
          {
            id: "lec-12",
            title: "State Management Patterns",
            duration: 50,
            type: "video",
          },
          { id: "lec-13", title: "Hooks Quiz", duration: 20, type: "quiz" },
        ],
      },
      {
        id: "section-3",
        title: "Advanced React Concepts",
        duration: 300,
        lectures: [
          {
            id: "lec-14",
            title: "Higher-Order Components",
            duration: 35,
            type: "video",
          },
          {
            id: "lec-15",
            title: "Render Props Pattern",
            duration: 40,
            type: "video",
          },
          {
            id: "lec-16",
            title: "React Performance Optimization",
            duration: 55,
            type: "video",
          },
          {
            id: "lec-17",
            title: "Error Boundaries",
            duration: 25,
            type: "video",
          },
          { id: "lec-18", title: "React Testing", duration: 60, type: "video" },
          {
            id: "lec-19",
            title: "Advanced Patterns Quiz",
            duration: 25,
            type: "quiz",
          },
          {
            id: "lec-20",
            title: "Final Project",
            duration: 60,
            type: "assignment",
          },
        ],
      },
    ],
    reviews: [
      {
        id: "review-1",
        userId: "user-1",
        rating: 5,
        comment:
          "Excellent course! John explains everything clearly and the projects are very practical. Highly recommended!",
        createdBy: "user-1",
        user: {
          id: "user-1",
          name: "Sarah Johnson",
          avatar:
            "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=40&h=40&fit=crop&crop=face",
        },
      },
      {
        id: "review-2",
        userId: "user-2",
        rating: 5,
        comment:
          "This course transformed my career. The content is up-to-date and the teaching method is outstanding.",
        createdBy: "user-2",
        user: {
          id: "user-2",
          name: "Mike Chen",
          avatar:
            "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop&crop=face",
        },
      },
    ],
  },
  {
    id: "course-2",
    instructorId: "inst-2",
    title: "Python for Data Science & Machine Learning",
    subtitle:
      "Master Data Analysis, Visualization & Machine Learning with Python",
    description:
      "Complete Python course for data science and machine learning. Learn pandas, numpy, matplotlib, scikit-learn, and more. Build real-world data science projects from scratch.",
    thumbnail:
      "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=225&fit=crop",
    trailerVideo:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    status: "Published",
    duration: 3600, // 60 hours
    price: 0, // Free
    level: "Beginner",
    categoryId: "cat-3",
    language: "English",
    numberOfReviews: 2100,
    averageRating: 4.8,
    totalStudents: 89450,
    lastUpdated: "2024-09-20",
    certificate: true,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[2],
    instructor: {
      id: "inst-2",
      name: "Sarah Johnson",
      profilePicture:
        "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=64&h=64&fit=crop&crop=face",
      bio: "Data Scientist and Machine Learning Engineer at Google. PhD in Computer Science with 10+ years of experience in AI and data science.",
      rating: 4.9,
      studentsCount: 125000,
      coursesCount: 8,
    },
    whatYouWillLearn: [
      "Master Python programming fundamentals",
      "Data manipulation with pandas and numpy",
      "Data visualization with matplotlib and seaborn",
      "Machine learning with scikit-learn",
      "Statistical analysis and hypothesis testing",
      "Build predictive models and algorithms",
      "Work with real datasets and case studies",
    ],
    requirements: [
      "Basic computer skills",
      "No prior programming experience required",
      "Access to a computer with internet connection",
    ],
    targetAudience: [
      "Complete beginners interested in data science",
      "Programmers wanting to learn Python",
      "Students pursuing data science careers",
      "Professionals looking to upskill in ML",
      "Anyone interested in data analysis",
    ],
    curriculum: [
      {
        id: "section-1",
        title: "Python Fundamentals",
        duration: 240,
        lectures: [
          {
            id: "lec-1",
            title: "Introduction to Python",
            duration: 20,
            type: "video",
            preview: true,
          },
          {
            id: "lec-2",
            title: "Installing Python and Setup",
            duration: 15,
            type: "video",
            preview: true,
          },
          {
            id: "lec-3",
            title: "Variables and Data Types",
            duration: 25,
            type: "video",
          },
          {
            id: "lec-4",
            title: "Control Structures",
            duration: 35,
            type: "video",
          },
          {
            id: "lec-5",
            title: "Functions and Modules",
            duration: 40,
            type: "video",
          },
          {
            id: "lec-6",
            title: "Python Fundamentals Quiz",
            duration: 25,
            type: "quiz",
          },
        ],
      },
      {
        id: "section-2",
        title: "Data Analysis with Pandas",
        duration: 300,
        lectures: [
          {
            id: "lec-7",
            title: "Introduction to Pandas",
            duration: 30,
            type: "video",
          },
          {
            id: "lec-8",
            title: "DataFrames and Series",
            duration: 45,
            type: "video",
          },
          {
            id: "lec-9",
            title: "Data Cleaning and Preprocessing",
            duration: 50,
            type: "video",
          },
          {
            id: "lec-10",
            title: "Data Aggregation and Grouping",
            duration: 40,
            type: "video",
          },
          {
            id: "lec-11",
            title: "Merging and Joining Data",
            duration: 35,
            type: "video",
          },
          {
            id: "lec-12",
            title: "Data Analysis Project",
            duration: 60,
            type: "assignment",
          },
          { id: "lec-13", title: "Pandas Quiz", duration: 20, type: "quiz" },
        ],
      },
      {
        id: "section-3",
        title: "Data Visualization",
        duration: 180,
        lectures: [
          {
            id: "lec-14",
            title: "Introduction to Matplotlib",
            duration: 30,
            type: "video",
          },
          {
            id: "lec-15",
            title: "Advanced Plotting with Seaborn",
            duration: 40,
            type: "video",
          },
          {
            id: "lec-16",
            title: "Interactive Visualizations",
            duration: 35,
            type: "video",
          },
          {
            id: "lec-17",
            title: "Visualization Project",
            duration: 55,
            type: "assignment",
          },
          {
            id: "lec-18",
            title: "Visualization Quiz",
            duration: 20,
            type: "quiz",
          },
        ],
      },
      {
        id: "section-4",
        title: "Machine Learning with Scikit-learn",
        duration: 360,
        lectures: [
          {
            id: "lec-19",
            title: "Introduction to Machine Learning",
            duration: 40,
            type: "video",
          },
          {
            id: "lec-20",
            title: "Supervised Learning Algorithms",
            duration: 60,
            type: "video",
          },
          {
            id: "lec-21",
            title: "Unsupervised Learning",
            duration: 50,
            type: "video",
          },
          {
            id: "lec-22",
            title: "Model Evaluation and Validation",
            duration: 45,
            type: "video",
          },
          {
            id: "lec-23",
            title: "Feature Engineering",
            duration: 35,
            type: "video",
          },
          {
            id: "lec-24",
            title: "ML Project: Predictive Modeling",
            duration: 70,
            type: "assignment",
          },
          {
            id: "lec-25",
            title: "Machine Learning Quiz",
            duration: 30,
            type: "quiz",
          },
        ],
      },
    ],
    reviews: [
      {
        id: "review-3",
        userId: "user-3",
        rating: 5,
        comment:
          "Perfect course for beginners! Sarah explains everything so clearly. I went from knowing nothing about Python to building ML models.",
        createdBy: "user-3",
        user: {
          id: "user-3",
          name: "Alex Chen",
          avatar:
            "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=40&h=40&fit=crop&crop=face",
        },
      },
      {
        id: "review-4",
        userId: "user-4",
        rating: 5,
        comment:
          "Free course with incredible quality! The projects are very practical and the instructor is amazing. Highly recommended!",
        createdBy: "user-4",
        user: {
          id: "user-4",
          name: "Maria Garcia",
          avatar:
            "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=40&h=40&fit=crop&crop=face",
        },
      },
    ],
  },
  {
    id: "course-3",
    instructorId: "inst-3",
    title: "iOS Development with SwiftUI",
    description:
      "Build beautiful iOS apps using SwiftUI framework. Learn declarative UI development and modern iOS patterns.",
    thumbnail:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=225&fit=crop",
    status: "Published",
    duration: 3000, // 50 hours
    price: 119.99,
    level: "Intermediate",
    categoryId: "cat-2",
    language: "English",
    numberOfReviews: 890,
    averageRating: 4.6,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[1],
    instructor: {
      id: "inst-3",
      name: "Mike Chen",
      profilePicture:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-4",
    instructorId: "inst-4",
    title: "UI/UX Design Masterclass",
    description:
      "Complete guide to user interface and user experience design. From wireframes to prototypes using Figma.",
    thumbnail:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=225&fit=crop",
    status: "Published",
    duration: 1800, // 30 hours
    price: 79.99,
    level: "Beginner",
    categoryId: "cat-4",
    language: "English",
    numberOfReviews: 650,
    averageRating: 4.5,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[3],
    instructor: {
      id: "inst-4",
      name: "Emily Davis",
      profilePicture:
        "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-5",
    instructorId: "inst-5",
    title: "Node.js Backend Development",
    description:
      "Build scalable backend applications with Node.js, Express, and MongoDB. REST APIs and GraphQL.",
    thumbnail:
      "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=225&fit=crop",
    status: "Published",
    duration: 2700, // 45 hours
    price: 94.99,
    level: "Intermediate",
    categoryId: "cat-1",
    language: "English",
    numberOfReviews: 980,
    averageRating: 4.4,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[0],
    instructor: {
      id: "inst-5",
      name: "David Wilson",
      profilePicture:
        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-6",
    instructorId: "inst-6",
    title: "Digital Marketing Strategy",
    description:
      "Master digital marketing from SEO to social media. Build comprehensive marketing strategies for businesses.",
    thumbnail:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=225&fit=crop",
    status: "Published",
    duration: 2100, // 35 hours
    price: 69.99,
    level: "Beginner",
    categoryId: "cat-5",
    language: "English",
    numberOfReviews: 720,
    averageRating: 4.3,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[4],
    instructor: {
      id: "inst-6",
      name: "Lisa Anderson",
      profilePicture:
        "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-7",
    instructorId: "inst-7",
    title: "Advanced JavaScript Concepts",
    description:
      "Deep dive into advanced JavaScript topics: closures, prototypes, async programming, and modern ES6+ features.",
    thumbnail:
      "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=400&h=225&fit=crop",
    status: "Published",
    duration: 3300, // 55 hours
    price: 129.99,
    level: "Advanced",
    categoryId: "cat-1",
    language: "English",
    numberOfReviews: 560,
    averageRating: 4.6,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[0],
    instructor: {
      id: "inst-7",
      name: "Alex Rodriguez",
      profilePicture:
        "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-8",
    instructorId: "inst-8",
    title: "Flutter Mobile App Development",
    description:
      "Create cross-platform mobile apps with Flutter and Dart. From basics to advanced state management.",
    thumbnail:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=225&fit=crop",
    status: "Published",
    duration: 3900, // 65 hours
    price: 109.99,
    level: "Intermediate",
    categoryId: "cat-2",
    language: "English",
    numberOfReviews: 430,
    averageRating: 4.7,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[1],
    instructor: {
      id: "inst-8",
      name: "Rachel Kim",
      profilePicture:
        "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-9",
    instructorId: "inst-9",
    title: "Machine Learning with TensorFlow",
    description:
      "Learn machine learning and deep learning with TensorFlow. Build and deploy ML models from scratch.",
    thumbnail:
      "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=225&fit=crop",
    status: "Published",
    duration: 4200, // 70 hours
    price: 149.99,
    level: "Advanced",
    categoryId: "cat-3",
    language: "English",
    numberOfReviews: 340,
    averageRating: 4.8,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[2],
    instructor: {
      id: "inst-9",
      name: "Dr. Michael Lee",
      profilePicture:
        "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-10",
    instructorId: "inst-10",
    title: "Graphic Design Fundamentals",
    description:
      "Master the fundamentals of graphic design. Learn Adobe Creative Suite and design principles.",
    thumbnail:
      "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=400&h=225&fit=crop",
    status: "Published",
    duration: 2400, // 40 hours
    price: 84.99,
    level: "Beginner",
    categoryId: "cat-4",
    language: "English",
    numberOfReviews: 780,
    averageRating: 4.4,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[3],
    instructor: {
      id: "inst-10",
      name: "Tom Garcia",
      profilePicture:
        "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-11",
    instructorId: "inst-11",
    title: "Startup Business Planning",
    description:
      "Learn how to create a winning business plan for your startup. From idea validation to funding strategies.",
    thumbnail:
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=225&fit=crop",
    status: "Published",
    duration: 1800, // 30 hours
    price: 59.99,
    level: "Beginner",
    categoryId: "cat-5",
    language: "English",
    numberOfReviews: 290,
    averageRating: 4.2,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[4],
    instructor: {
      id: "inst-11",
      name: "Jennifer White",
      profilePicture:
        "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=64&h=64&fit=crop&crop=face",
    },
  },
  {
    id: "course-12",
    instructorId: "inst-12",
    title: "Vue.js 3 Complete Guide",
    description:
      "Master Vue.js 3 with Composition API, Pinia state management, and modern frontend development practices.",
    thumbnail:
      "https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=400&h=225&fit=crop",
    status: "Published",
    duration: 2700, // 45 hours
    price: 99.99,
    level: "Intermediate",
    categoryId: "cat-1",
    language: "English",
    numberOfReviews: 420,
    averageRating: 4.5,
    createdBy: "system",
    updatedAt: null,
    updatedBy: null,
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    category: mockCategories[0],
    instructor: {
      id: "inst-12",
      name: "Kevin Brown",
      profilePicture:
        "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=64&h=64&fit=crop&crop=face",
    },
  },
];

// Mock enrolled courses (courses user is currently taking)
export const mockEnrolledCourses = [
  {
    id: "enrolled-1",
    userId: "user-1",
    courseId: "course-1",
    enrollmentDate: "2024-01-15",
    lastAccessedDate: "2024-10-25",
    progressPercentage: 75,
    completedLectures: 15,
    totalLectures: 20,
    status: "in_progress",
    certificateEarned: false,
    createdBy: "system",
    updatedAt: "2024-10-25",
    updatedBy: "system",
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    course: mockCourses[0], // React course
  },
  {
    id: "enrolled-2",
    userId: "user-1",
    courseId: "course-2",
    enrollmentDate: "2024-02-20",
    lastAccessedDate: "2024-10-20",
    progressPercentage: 100,
    completedLectures: 25,
    totalLectures: 25,
    status: "completed",
    certificateEarned: true,
    certificateUrl: "https://example.com/certificates/python-cert-123",
    createdBy: "system",
    updatedAt: "2024-10-20",
    updatedBy: "system",
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    course: mockCourses[1], // Python course
  },
  {
    id: "enrolled-3",
    userId: "user-1",
    courseId: "course-3",
    enrollmentDate: "2024-09-10",
    lastAccessedDate: "2024-10-28",
    progressPercentage: 45,
    completedLectures: 9,
    totalLectures: 20,
    status: "in_progress",
    certificateEarned: false,
    createdBy: "system",
    updatedAt: "2024-10-28",
    updatedBy: "system",
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    course: mockCourses[2], // iOS course
  },
];

// Mock wishlist items (courses user wants to take later)
export const mockWishlistItems = [
  {
    id: "wishlist-1",
    userId: "user-1",
    courseId: "course-4",
    addedDate: "2024-08-15",
    createdBy: "system",
    updatedAt: "2024-08-15",
    updatedBy: "system",
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    course: mockCourses[3], // UI/UX course
  },
  {
    id: "wishlist-2",
    userId: "user-1",
    courseId: "course-7",
    addedDate: "2024-09-01",
    createdBy: "system",
    updatedAt: "2024-09-01",
    updatedBy: "system",
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    course: mockCourses[6], // Advanced JavaScript course
  },
  {
    id: "wishlist-3",
    userId: "user-1",
    courseId: "course-9",
    addedDate: "2024-10-10",
    createdBy: "system",
    updatedAt: "2024-10-10",
    updatedBy: "system",
    isDeleted: false,
    deletedAt: null,
    deletedBy: null,
    course: mockCourses[8], // Machine Learning course
  },
];
export const mockCourse: Course = {
  id: "course-learn-1",
  title: "Complete Web Development Bootcamp",
  description:
    "Master modern web development from HTML to advanced JavaScript frameworks. Build real-world projects and learn industry best practices.",
  thumbnail:
    "https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&h=450&fit=crop",
  status: "Published",
  duration: 4800, // 80 hours in minutes
  price: 99.99,
  level: "Intermediate",
  numReviews: 1250,
  averageRating: 4.7,
  createdAt: "2024-01-15T10:00:00Z",
  updatedAt: "2024-10-15T14:30:00Z",
  createdBy: "system",
  updatedBy: "system",
  isDeleted: false,
  deletedAt: null,
  deletedBy: undefined,
  modules: [
    {
      id: "module-1",
      title: "HTML & CSS Fundamentals",
      duration: 720,
      numLessons: 8,
      order: 1,
      courseId: "course-learn-1",
      createdAt: "2024-01-15T10:00:00Z",
      updatedAt: "2024-01-15T10:00:00Z",
      createdBy: "system",
      updatedBy: "system",
      isDeleted: false,
      deletedAt: null,
      deletedBy: undefined,
      lessons: [
        {
          id: "lesson-1-1",
          title: "Introduction to HTML",
          moduleId: "module-1",
          rawContent:
            "# Introduction to HTML\n\nHTML (HyperText Markup Language) is the standard markup language for creating web pages.\n\n## What is HTML?\n\nHTML is not a programming language; it is a markup language that tells web browsers how to structure the web pages you visit.\n\n## Basic Structure\n\n```html\n<!DOCTYPE html>\n<html>\n<head>\n    <title>My First Web Page</title>\n</head>\n<body>\n    <h1>Hello World!</h1>\n    <p>This is my first paragraph.</p>\n</body>\n</html>\n```",
          contentUrl: "",
          duration: 15,
          orderIndex: 1,
          isPreviewable: true,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-1-2",
          title: "HTML Elements and Tags",
          moduleId: "module-1",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
          duration: 25,
          orderIndex: 2,
          isPreviewable: true,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-1-3",
          title: "CSS Basics",
          moduleId: "module-1",
          rawContent:
            "# CSS Basics\n\nCSS (Cascading Style Sheets) is used to describe the presentation of a document written in HTML.\n\n## What is CSS?\n\nCSS describes how HTML elements should be displayed on screen, paper, or in other media.\n\n## Ways to Add CSS\n\n1. **Inline CSS**: Using the style attribute\n2. **Internal CSS**: Using <style> tag in <head>\n3. **External CSS**: Using external .css file\n\n## CSS Syntax\n\n```css\nselector {\n    property: value;\n    property: value;\n}\n```\n\n## Example\n\n```css\nh1 {\n    color: blue;\n    font-size: 24px;\n}\n\np {\n    color: green;\n    font-family: Arial, sans-serif;\n}\n```",
          contentUrl: "",
          duration: 20,
          orderIndex: 3,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-1-4",
          title: "CSS Selectors and Properties",
          moduleId: "module-1",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
          duration: 30,
          orderIndex: 4,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-1-5",
          title: "Building Your First Website",
          moduleId: "module-1",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
          duration: 35,
          orderIndex: 5,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-1-6",
          title: "Responsive Design with CSS",
          moduleId: "module-1",
          rawContent:
            "# Responsive Design\n\nResponsive web design makes your web pages look good on all devices.\n\n## Media Queries\n\nMedia queries allow you to apply CSS rules based on device characteristics.\n\n```css\n/* Mobile First */\n.container {\n    width: 100%;\n}\n\n/* Tablet */\n@media (min-width: 768px) {\n    .container {\n        width: 750px;\n    }\n}\n\n/* Desktop */\n@media (min-width: 992px) {\n    .container {\n        width: 970px;\n    }\n}\n```\n\n## Flexible Layouts\n\nUse percentage widths and flexible units like em, rem, and vh/vw.",
          contentUrl: "",
          duration: 25,
          orderIndex: 6,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-1-7",
          title: "CSS Flexbox",
          moduleId: "module-1",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
          duration: 40,
          orderIndex: 7,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-1-8",
          title: "HTML & CSS Fundamentals Quiz",
          moduleId: "module-1",
          rawContent: "",
          contentUrl: "",
          duration: 15,
          orderIndex: 8,
          isPreviewable: false,
          lessonType: "quiz",
          quiz: {
            id: "quiz-1-1",
            title: "HTML & CSS Fundamentals Quiz",
            description: "Test your knowledge of HTML and CSS basics",
            totalMarks: 10,
            passingScore: 7,
            createdAt: "2024-01-15T10:00:00Z",
            updatedAt: "2024-01-15T10:00:00Z",
            createdBy: "system",
            updatedBy: "system",
            isDeleted: false,
            deletedAt: null,
            deletedBy: undefined,
            quizQuestions: [
              {
                id: "q-1-1",
                questionText: "What does HTML stand for?",
                type: "multiple_choice",
                marks: 2,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-1-1-1",
                    text: "HyperText Markup Language",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-1-2",
                    text: "High Tech Modern Language",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-1-3",
                    text: "Hyperlink and Text Markup Language",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-1-4",
                    text: "Home Tool Markup Language",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
              {
                id: "q-1-2",
                questionText:
                  "Which CSS property is used to change the text color?",
                type: "multiple_choice",
                marks: 2,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-1-2-1",
                    text: "font-color",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-2-2",
                    text: "text-color",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-2-3",
                    text: "color",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-2-4",
                    text: "foreground-color",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
              {
                id: "q-1-3",
                questionText: "HTML is a programming language.",
                type: "true_false",
                marks: 1,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-1-3-1",
                    text: "True",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-3-2",
                    text: "False",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
              {
                id: "q-1-4",
                questionText:
                  "Which of the following is used to define a CSS class selector?",
                type: "single_choice",
                marks: 2,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-1-4-1",
                    text: "#classname",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-4-2",
                    text: ".classname",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-4-3",
                    text: "classname",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-4-4",
                    text: "@classname",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
              {
                id: "q-1-5",
                questionText:
                  "Explain what CSS stands for and its primary purpose in web development.",
                type: "short_answer",
                marks: 3,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-1-5-1",
                    text: "Cascading Style Sheets - used to describe the presentation of a document written in HTML",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-1-5-2",
                    text: "CSS stands for Cascading Style Sheets and is used for styling web pages",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
            ],
          },
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
      ],
    },
    {
      id: "module-2",
      title: "JavaScript Fundamentals",
      duration: 960,
      numLessons: 10,
      order: 2,
      courseId: "course-learn-1",
      createdAt: "2024-01-15T10:00:00Z",
      updatedAt: "2024-01-15T10:00:00Z",
      createdBy: "system",
      updatedBy: "system",
      isDeleted: false,
      deletedAt: null,
      deletedBy: undefined,
      lessons: [
        {
          id: "lesson-2-1",
          title: "Introduction to JavaScript",
          moduleId: "module-2",
          rawContent:
            "# Introduction to JavaScript\n\nJavaScript is a versatile programming language that powers the web.\n\n## What is JavaScript?\n\nJavaScript is a high-level, interpreted programming language that conforms to the ECMAScript specification. It is primarily used for web development but can also be used for server-side programming.\n\n## Key Features\n\n- **Dynamic typing**: Variables can hold different types of values\n- **First-class functions**: Functions are treated as first-class citizens\n- **Prototype-based**: Uses prototypes instead of classes (though classes were added in ES6)\n- **Event-driven**: Responds to user interactions and events\n\n## Basic Syntax\n\n```javascript\n// Variables\nlet name = 'JavaScript';\nconst version = 'ES6+';\nvar oldWay = 'deprecated';\n\n// Functions\nfunction greet(name) {\n    return `Hello, ${name}!`;\n}\n\n// Arrow functions\nconst greet = (name) => `Hello, ${name}!`;\n```",
          contentUrl: "",
          duration: 20,
          orderIndex: 1,
          isPreviewable: true,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-2-2",
          title: "Variables and Data Types",
          moduleId: "module-2",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
          duration: 25,
          orderIndex: 2,
          isPreviewable: true,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-2-3",
          title: "Functions and Scope",
          moduleId: "module-2",
          rawContent:
            "# Functions and Scope\n\nFunctions are the building blocks of JavaScript applications.\n\n## Function Declaration\n\n```javascript\nfunction add(a, b) {\n    return a + b;\n}\n```\n\n## Function Expression\n\n```javascript\nconst add = function(a, b) {\n    return a + b;\n};\n```\n\n## Arrow Functions\n\n```javascript\nconst add = (a, b) => a + b;\n```\n\n## Scope\n\n- **Global Scope**: Variables accessible everywhere\n- **Function Scope**: Variables accessible within functions\n- **Block Scope**: Variables accessible within blocks (let/const)\n\n## Closures\n\nA closure is a function that has access to variables in its outer scope.\n\n```javascript\nfunction createCounter() {\n    let count = 0;\n    return function() {\n        return ++count;\n    };\n}\n\nconst counter = createCounter();\nconsole.log(counter()); // 1\nconsole.log(counter()); // 2\n```",
          contentUrl: "",
          duration: 30,
          orderIndex: 3,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-2-4",
          title: "Arrays and Objects",
          moduleId: "module-2",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
          duration: 35,
          orderIndex: 4,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-2-5",
          title: "DOM Manipulation",
          moduleId: "module-2",
          rawContent:
            "# DOM Manipulation\n\nThe Document Object Model (DOM) is a programming interface for web documents.\n\n## Selecting Elements\n\n```javascript\n// By ID\ndocument.getElementById('myId');\n\n// By class\ndocument.getElementsByClassName('myClass');\n\n// By tag\ndocument.getElementsByTagName('div');\n\n// Modern way\ndocument.querySelector('#myId');\ndocument.querySelectorAll('.myClass');\n```\n\n## Modifying Elements\n\n```javascript\nconst element = document.querySelector('#myElement');\n\n// Change text\nelement.textContent = 'New text';\nelement.innerHTML = '<strong>New HTML</strong>';\n\n// Change attributes\nelement.setAttribute('class', 'new-class');\nelement.classList.add('another-class');\n\n// Change styles\nelement.style.color = 'red';\nelement.style.fontSize = '20px';\n```\n\n## Event Handling\n\n```javascript\nconst button = document.querySelector('#myButton');\n\nbutton.addEventListener('click', function(event) {\n    console.log('Button clicked!');\n    event.preventDefault();\n});\n\n// Or with arrow function\nbutton.addEventListener('click', (event) => {\n    console.log('Button clicked!');\n});\n```",
          contentUrl: "",
          duration: 40,
          orderIndex: 5,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-2-6",
          title: "Asynchronous JavaScript",
          moduleId: "module-2",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
          duration: 45,
          orderIndex: 6,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-2-7",
          title: "ES6+ Features",
          moduleId: "module-2",
          rawContent:
            "# ES6+ Features\n\nModern JavaScript features that make coding more efficient.\n\n## Destructuring\n\n```javascript\n// Array destructuring\nconst [a, b, c] = [1, 2, 3];\n\n// Object destructuring\nconst {name, age} = {name: 'John', age: 30};\n```\n\n## Template Literals\n\n```javascript\nconst name = 'World';\nconst greeting = `Hello, ${name}!`;\n\n// Multi-line strings\nconst html = `\n  <div>\n    <h1>${title}</h1>\n    <p>${content}</p>\n  </div>\n`;\n```\n\n## Spread Operator\n\n```javascript\nconst arr1 = [1, 2, 3];\nconst arr2 = [...arr1, 4, 5]; // [1, 2, 3, 4, 5]\n\nconst obj1 = {a: 1, b: 2};\nconst obj2 = {...obj1, c: 3}; // {a: 1, b: 2, c: 3}\n```\n\n## Promises and Async/Await\n\n```javascript\nfunction fetchData() {\n    return new Promise((resolve, reject) => {\n        setTimeout(() => {\n            resolve('Data fetched');\n        }, 1000);\n    });\n}\n\n// Using promises\nfetchData().then(data => console.log(data));\n\n// Using async/await\nasync function getData() {\n    try {\n        const data = await fetchData();\n        console.log(data);\n    } catch (error) {\n        console.error(error);\n    }\n}\n```",
          contentUrl: "",
          duration: 35,
          orderIndex: 7,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-2-8",
          title: "Error Handling",
          moduleId: "module-2",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
          duration: 25,
          orderIndex: 8,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-2-9",
          title: "JavaScript Best Practices",
          moduleId: "module-2",
          rawContent:
            "# JavaScript Best Practices\n\nWriting clean, maintainable JavaScript code.\n\n## Code Style\n\n- Use consistent indentation (2 spaces)\n- Use semicolons\n- Use camelCase for variables and functions\n- Use PascalCase for classes and constructors\n- Use UPPER_CASE for constants\n\n## Naming Conventions\n\n```javascript\n// Good\nconst userName = 'john_doe';\nconst MAX_USERS = 100;\n\nfunction calculateTotal(price, tax) {\n    return price + (price * tax);\n}\n\nclass UserManager {\n    constructor() {\n        this.users = [];\n    }\n}\n```\n\n## Avoid Global Variables\n\n```javascript\n// Bad\nvar globalVar = 'I am global';\n\n// Good\n(function() {\n    var localVar = 'I am local';\n})();\n```\n\n## Use Strict Mode\n\n```javascript\n'use strict';\n\n// This enables stricter parsing and error handling\n```\n\n## Error Handling\n\n```javascript\ntry {\n    // Code that might throw an error\n    riskyOperation();\n} catch (error) {\n    console.error('An error occurred:', error);\n} finally {\n    // Cleanup code\n    cleanup();\n}\n```",
          contentUrl: "",
          duration: 30,
          orderIndex: 9,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-2-10",
          title: "JavaScript Fundamentals Quiz",
          moduleId: "module-2",
          rawContent: "",
          contentUrl: "",
          duration: 20,
          orderIndex: 10,
          isPreviewable: false,
          lessonType: "quiz",
          quiz: {
            id: "quiz-2-1",
            title: "JavaScript Fundamentals Quiz",
            description: "Test your knowledge of JavaScript basics",
            totalMarks: 15,
            passingScore: 11,
            createdAt: "2024-01-15T10:00:00Z",
            updatedAt: "2024-01-15T10:00:00Z",
            createdBy: "system",
            updatedBy: "system",
            isDeleted: false,
            deletedAt: null,
            deletedBy: undefined,
            quizQuestions: [
              {
                id: "q-2-1",
                questionText:
                  "Which keyword is used to declare a block-scoped variable?",
                type: "single_choice",
                marks: 1,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-2-1-1",
                    text: "var",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-2-1-2",
                    text: "let",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-2-1-3",
                    text: "const",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
              {
                id: "q-2-2",
                questionText: "JavaScript is a compiled language.",
                type: "true_false",
                marks: 1,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-2-2-1",
                    text: "True",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-2-2-2",
                    text: "False",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
              {
                id: "q-2-3",
                questionText: "What does DOM stand for?",
                type: "short_answer",
                marks: 2,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-2-3-1",
                    text: "Document Object Model",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
            ],
          },
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
      ],
    },
    {
      id: "module-3",
      title: "React.js Fundamentals",
      duration: 1200,
      numLessons: 12,
      order: 3,
      courseId: "course-learn-1",
      createdAt: "2024-01-15T10:00:00Z",
      updatedAt: "2024-01-15T10:00:00Z",
      createdBy: "system",
      updatedBy: "system",
      isDeleted: false,
      deletedAt: null,
      deletedBy: undefined,
      lessons: [
        {
          id: "lesson-3-1",
          title: "Introduction to React",
          moduleId: "module-3",
          rawContent:
            '# Introduction to React\n\nReact is a JavaScript library for building user interfaces.\n\n## What is React?\n\nReact is a declarative, efficient, and flexible JavaScript library for building user interfaces. It lets you compose complex UIs from small and isolated pieces of code called components.\n\n## Key Concepts\n\n- **Components**: Reusable pieces of UI\n- **JSX**: Syntax extension for JavaScript\n- **Virtual DOM**: In-memory representation of the real DOM\n- **One-way data flow**: Data flows down from parent to child components\n\n## Why React?\n\n- **Declarative**: Describe what you want, not how to do it\n- **Component-based**: Build encapsulated components\n- **Learn once, write anywhere**: Use React for web, mobile, etc.\n- **Developer tools**: Excellent debugging experience\n\n## Basic Component\n\n```jsx\nfunction Welcome(props) {\n  return <h1>Hello, {props.name}!</h1>;\n}\n\n// Usage\n<Welcome name="World" />\n```',
          contentUrl: "",
          duration: 25,
          orderIndex: 1,
          isPreviewable: true,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-2",
          title: "JSX and Rendering",
          moduleId: "module-3",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
          duration: 30,
          orderIndex: 2,
          isPreviewable: true,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-3",
          title: "Components and Props",
          moduleId: "module-3",
          rawContent:
            '# Components and Props\n\nComponents are the building blocks of React applications.\n\n## Function Components\n\n```jsx\nfunction Welcome(props) {\n  return <h1>Hello, {props.name}!</h1>;\n}\n\n// Or with arrow function\nconst Welcome = (props) => {\n  return <h1>Hello, {props.name}!</h1>;\n};\n```\n\n## Class Components\n\n```jsx\nclass Welcome extends React.Component {\n  render() {\n    return <h1>Hello, {this.props.name}!</h1>;\n  }\n}\n```\n\n## Props\n\nProps are how data flows from parent to child components.\n\n```jsx\nfunction UserCard({ name, age, email }) {\n  return (\n    <div>\n      <h2>{name}</h2>\n      <p>Age: {age}</p>\n      <p>Email: {email}</p>\n    </div>\n  );\n}\n\n// Usage\n<UserCard name="John" age={30} email="john@example.com" />\n```\n\n## Default Props\n\n```jsx\nfunction Greeting({ name = "Guest" }) {\n  return <h1>Hello, {name}!</h1>;\n}\n```\n\n## Prop Types (TypeScript)\n\n```tsx\ninterface UserCardProps {\n  name: string;\n  age: number;\n  email: string;\n}\n\nfunction UserCard({ name, age, email }: UserCardProps) {\n  // ...\n}\n```',
          contentUrl: "",
          duration: 35,
          orderIndex: 3,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-4",
          title: "State and Lifecycle",
          moduleId: "module-3",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
          duration: 40,
          orderIndex: 4,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-5",
          title: "Hooks Introduction",
          moduleId: "module-3",
          rawContent:
            "# React Hooks\n\nHooks are functions that let you use state and lifecycle features in function components.\n\n## useState\n\n```jsx\nimport { useState } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>\n        Increment\n      </button>\n    </div>\n  );\n}\n```\n\n## useEffect\n\n```jsx\nimport { useEffect, useState } from 'react';\n\nfunction DataFetcher() {\n  const [data, setData] = useState(null);\n  const [loading, setLoading] = useState(true);\n\n  useEffect(() => {\n    fetch('/api/data')\n      .then(response => response.json())\n      .then(data => {\n        setData(data);\n        setLoading(false);\n      });\n  }, []); // Empty dependency array = run once\n\n  if (loading) return <div>Loading...</div>;\n  return <div>{JSON.stringify(data)}</div>;\n}\n```\n\n## Rules of Hooks\n\n1. Only call hooks at the top level\n2. Only call hooks from React functions\n3. Hooks can be called conditionally, but the order must be consistent\n\n## Custom Hooks\n\n```jsx\nfunction useLocalStorage(key, initialValue) {\n  const [storedValue, setStoredValue] = useState(() => {\n    try {\n      const item = window.localStorage.getItem(key);\n      return item ? JSON.parse(item) : initialValue;\n    } catch (error) {\n      return initialValue;\n    }\n  });\n\n  const setValue = (value) => {\n    try {\n      setStoredValue(value);\n      window.localStorage.setItem(key, JSON.stringify(value));\n    } catch (error) {\n      console.error(error);\n    }\n  };\n\n  return [storedValue, setValue];\n}\n```",
          contentUrl: "",
          duration: 45,
          orderIndex: 5,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-6",
          title: "Event Handling",
          moduleId: "module-3",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
          duration: 30,
          orderIndex: 6,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-7",
          title: "Conditional Rendering",
          moduleId: "module-3",
          rawContent:
            "# Conditional Rendering\n\nDifferent ways to conditionally render content in React.\n\n## If/Else Statements\n\n```jsx\nfunction Greeting({ isLoggedIn }) {\n  if (isLoggedIn) {\n    return <h1>Welcome back!</h1>;\n  }\n  return <h1>Please sign in.</h1>;\n}\n```\n\n## Ternary Operator\n\n```jsx\nfunction Greeting({ isLoggedIn }) {\n  return (\n    <h1>\n      {isLoggedIn ? 'Welcome back!' : 'Please sign in.'}\n    </h1>\n  );\n}\n```\n\n## Logical && Operator\n\n```jsx\nfunction Mailbox({ messages }) {\n  return (\n    <div>\n      <h1>Hello!</h1>\n      {messages.length > 0 && (\n        <h2>\n          You have {messages.length} unread messages.\n        </h2>\n      )}\n    </div>\n  );\n}\n```\n\n## Switch Statement\n\n```jsx\nfunction Notification({ status }) {\n  switch (status) {\n    case 'loading':\n      return <div>Loading...</div>;\n    case 'success':\n      return <div>Success!</div>;\n    case 'error':\n      return <div>Error occurred!</div>;\n    default:\n      return null;\n  }\n}\n```\n\n## Preventing Rendering\n\n```jsx\nfunction WarningBanner({ showWarning }) {\n  if (!showWarning) {\n    return null;\n  }\n\n  return (\n    <div className=\"warning\">\n      Warning!\n    </div>\n  );\n}\n```",
          contentUrl: "",
          duration: 25,
          orderIndex: 7,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-8",
          title: "Lists and Keys",
          moduleId: "module-3",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
          duration: 35,
          orderIndex: 8,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-9",
          title: "Forms and Controlled Components",
          moduleId: "module-3",
          rawContent:
            '# Forms in React\n\nHandling form inputs with controlled components.\n\n## Controlled Components\n\n```jsx\nimport { useState } from \'react\';\n\nfunction NameForm() {\n  const [name, setName] = useState(\'\');\n\n  const handleSubmit = (event) => {\n    event.preventDefault();\n    alert(\'A name was submitted: \' + name);\n  };\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <label>\n        Name:\n        <input\n          type="text"\n          value={name}\n          onChange={(e) => setName(e.target.value)}\n        />\n      </label>\n      <button type="submit">Submit</button>\n    </form>\n  );\n}\n```\n\n## Multiple Inputs\n\n```jsx\nfunction Reservation() {\n  const [formData, setFormData] = useState({\n    isGoing: true,\n    numberOfGuests: 2,\n  });\n\n  const handleInputChange = (event) => {\n    const target = event.target;\n    const value = target.type === \'checkbox\' ? target.checked : target.value;\n    const name = target.name;\n\n    setFormData({\n      ...formData,\n      [name]: value,\n    });\n  };\n\n  return (\n    <form>\n      <label>\n        Is going:\n        <input\n          name="isGoing"\n          type="checkbox"\n          checked={formData.isGoing}\n          onChange={handleInputChange}\n        />\n      </label>\n      <br />\n      <label>\n        Number of guests:\n        <input\n          name="numberOfGuests"\n          type="number"\n          value={formData.numberOfGuests}\n          onChange={handleInputChange}\n        />\n      </label>\n    </form>\n  );\n}\n```\n\n## Form Libraries\n\nFor complex forms, consider using libraries like:\n- React Hook Form\n- Formik\n- React Final Form\n\nThese provide better performance and developer experience for complex forms.',
          contentUrl: "",
          duration: 40,
          orderIndex: 9,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-10",
          title: "Component Composition",
          moduleId: "module-3",
          rawContent: "",
          contentUrl:
            "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
          duration: 30,
          orderIndex: 10,
          isPreviewable: false,
          lessonType: "video",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-11",
          title: "React Best Practices",
          moduleId: "module-3",
          rawContent:
            "# React Best Practices\n\nGuidelines for writing maintainable React code.\n\n## Component Structure\n\n- Keep components small and focused\n- Use descriptive names\n- Extract reusable logic into custom hooks\n- Separate presentational and container components\n\n## State Management\n\n- Lift state up when needed\n- Use local state for component-specific data\n- Consider context for global state\n- Use reducers for complex state logic\n\n## Performance\n\n- Use React.memo for expensive components\n- Use useMemo and useCallback for expensive calculations\n- Avoid unnecessary re-renders\n- Use keys properly in lists\n\n## Code Organization\n\n```\nsrc/\n  components/\n    Button/\n      Button.tsx\n      Button.test.tsx\n      index.ts\n    Layout/\n      Header.tsx\n      Sidebar.tsx\n  hooks/\n    useAuth.ts\n    useLocalStorage.ts\n  utils/\n    formatDate.ts\n    api.ts\n```\n\n## Naming Conventions\n\n- Components: PascalCase (UserCard, Button)\n- Files: PascalCase for components, camelCase for utilities\n- Hooks: camelCase with 'use' prefix (useState, useAuth)\n- Props: camelCase (userName, onClick)\n\n## Accessibility\n\n- Use semantic HTML elements\n- Provide alt text for images\n- Ensure keyboard navigation\n- Use ARIA attributes when needed\n- Test with screen readers",
          contentUrl: "",
          duration: 35,
          orderIndex: 11,
          isPreviewable: false,
          lessonType: "markdown",
          quiz: null,
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
        {
          id: "lesson-3-12",
          title: "React Fundamentals Quiz",
          moduleId: "module-3",
          rawContent: "",
          contentUrl: "",
          duration: 25,
          orderIndex: 12,
          isPreviewable: false,
          lessonType: "quiz",
          quiz: {
            id: "quiz-3-1",
            title: "React Fundamentals Quiz",
            description: "Test your knowledge of React basics",
            totalMarks: 15,
            passingScore: 11,
            createdAt: "2024-01-15T10:00:00Z",
            updatedAt: "2024-01-15T10:00:00Z",
            createdBy: "system",
            updatedBy: "system",
            isDeleted: false,
            deletedAt: null,
            deletedBy: undefined,
            quizQuestions: [
              {
                id: "q-3-1",
                questionText: "What is JSX?",
                type: "multiple_choice",
                marks: 2,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-3-1-1",
                    text: "A JavaScript framework",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-3-1-2",
                    text: "A syntax extension for JavaScript",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-3-1-3",
                    text: "A CSS preprocessor",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
              {
                id: "q-3-2",
                questionText:
                  "Which hook is used to manage state in functional components?",
                type: "single_choice",
                marks: 1,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-3-2-1",
                    text: "useEffect",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-3-2-2",
                    text: "useState",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-3-2-3",
                    text: "useContext",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
              {
                id: "q-3-3",
                questionText:
                  "Props in React flow from parent to child components.",
                type: "true_false",
                marks: 1,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-3-3-1",
                    text: "True",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-3-3-2",
                    text: "False",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
              {
                id: "q-3-4",
                questionText:
                  "What is the purpose of the 'key' prop in React lists?",
                type: "short_answer",
                marks: 2,
                createdAt: "2024-01-15T10:00:00Z",
                updatedAt: "2024-01-15T10:00:00Z",
                createdBy: "system",
                updatedBy: "system",
                isDeleted: false,
                deletedAt: null,
                deletedBy: undefined,
                answers: [
                  {
                    id: "a-3-4-1",
                    text: "To help React identify which items have changed, are added, or are removed",
                    isCorrect: true,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                  {
                    id: "a-3-4-2",
                    text: "To style list items uniquely",
                    isCorrect: false,
                    createdAt: "2024-01-15T10:00:00Z",
                    updatedAt: "2024-01-15T10:00:00Z",
                    createdBy: "system",
                    updatedBy: "system",
                    isDeleted: false,
                    deletedAt: null,
                    deletedBy: undefined,
                  },
                ],
              },
            ],
          },
          createdAt: "2024-01-15T10:00:00Z",
          updatedAt: "2024-01-15T10:00:00Z",
          createdBy: "system",
          updatedBy: "system",
          isDeleted: false,
          deletedAt: null,
          deletedBy: undefined,
        },
      ],
    },
  ],
};
