/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as LecturingToolRouteRouteImport } from './routes/lecturing-tool/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as LecturingToolIndexRouteImport } from './routes/lecturing-tool/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as LecturingToolCourseIndexRouteImport } from './routes/lecturing-tool/course/index'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturingToolRouteRoute = LecturingToolRouteRouteImport.update({
  id: '/lecturing-tool',
  path: '/lecturing-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const LecturingToolIndexRoute = LecturingToolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LecturingToolRouteRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRouteRoute,
} as any)
const LecturingToolCourseIndexRoute =
  LecturingToolCourseIndexRouteImport.update({
    id: '/course/',
    path: '/course/',
    getParentRoute: () => LecturingToolRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lecturing-tool': typeof LecturingToolRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/lecturing-tool/': typeof LecturingToolIndexRoute
  '/users/': typeof UsersIndexRoute
  '/lecturing-tool/course': typeof LecturingToolCourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/lecturing-tool': typeof LecturingToolIndexRoute
  '/users': typeof UsersIndexRoute
  '/lecturing-tool/course': typeof LecturingToolCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lecturing-tool': typeof LecturingToolRouteRouteWithChildren
  '/users': typeof UsersRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/lecturing-tool/': typeof LecturingToolIndexRoute
  '/users/': typeof UsersIndexRoute
  '/lecturing-tool/course/': typeof LecturingToolCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lecturing-tool'
    | '/users'
    | '/about'
    | '/contact'
    | '/users/$userId'
    | '/lecturing-tool/'
    | '/users/'
    | '/lecturing-tool/course'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/users/$userId'
    | '/lecturing-tool'
    | '/users'
    | '/lecturing-tool/course'
  id:
    | '__root__'
    | '/'
    | '/lecturing-tool'
    | '/users'
    | '/about'
    | '/contact'
    | '/users/$userId'
    | '/lecturing-tool/'
    | '/users/'
    | '/lecturing-tool/course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LecturingToolRouteRoute: typeof LecturingToolRouteRouteWithChildren
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturing-tool': {
      id: '/lecturing-tool'
      path: '/lecturing-tool'
      fullPath: '/lecturing-tool'
      preLoaderRoute: typeof LecturingToolRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/lecturing-tool/': {
      id: '/lecturing-tool/'
      path: '/'
      fullPath: '/lecturing-tool/'
      preLoaderRoute: typeof LecturingToolIndexRouteImport
      parentRoute: typeof LecturingToolRouteRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/lecturing-tool/course/': {
      id: '/lecturing-tool/course/'
      path: '/course'
      fullPath: '/lecturing-tool/course'
      preLoaderRoute: typeof LecturingToolCourseIndexRouteImport
      parentRoute: typeof LecturingToolRouteRoute
    }
  }
}

interface LecturingToolRouteRouteChildren {
  LecturingToolIndexRoute: typeof LecturingToolIndexRoute
  LecturingToolCourseIndexRoute: typeof LecturingToolCourseIndexRoute
}

const LecturingToolRouteRouteChildren: LecturingToolRouteRouteChildren = {
  LecturingToolIndexRoute: LecturingToolIndexRoute,
  LecturingToolCourseIndexRoute: LecturingToolCourseIndexRoute,
}

const LecturingToolRouteRouteWithChildren =
  LecturingToolRouteRoute._addFileChildren(LecturingToolRouteRouteChildren)

interface UsersRouteRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LecturingToolRouteRoute: LecturingToolRouteRouteWithChildren,
  UsersRouteRoute: UsersRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
